##Tensorflow Basics

In [73]:
import numpy as np
import tensorflow as tf

print(tf.__version__)

1.13.1


 ***Constant*** :Constant can be created using **tf.constant()** function.

**tf.constant():**Creates a constant tensor.

The resulting tensor is populated with values of type dtype, as specified by arguments value and (optionally) shape (see examples below).




In [0]:
hello=tf.constant("Hello ")
world=tf.constant("Python")

In [6]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [7]:
print(hello)

Tensor("Const_2:0", shape=(), dtype=string)


In [0]:
with tf.Session() as sess:
  result=sess.run(hello+world)

In [10]:
print(result)

b'Hello Python'


In [18]:
# Constant 1-D Tensor populated with value list.
tensor = tf.constant([1, 2, 3, 4, 5, 6, 7]) 
print(tensor)

Tensor("Const_7:0", shape=(7,), dtype=int32)


In [19]:
with tf.Session() as sess:
  result=sess.run(tensor)
 
print(result)


[1 2 3 4 5 6 7]


In [20]:
# Constant 2-D tensor populated with scalar value -1.
tensor = tf.constant(-1.0, shape=[2, 3])
print(tensor)

Tensor("Const_8:0", shape=(2, 3), dtype=float32)


In [21]:
with tf.Session() as sess:
  result=sess.run(tensor)
 
print(result)

[[-1. -1. -1.]
 [-1. -1. -1.]]


###Variable:
A variable maintains state in the graph across calls to run(). You add a variable to the graph by constructing an instance of the **class Variable.**

The **Variable()** constructor requires an initial value for the variable, which can be a Tensor of any type and shape. The initial value defines the type and shape of the variable. After construction, the type and shape of the variable are fixed. The value can be changed using one of the assign methods.

If you want to change the shape of a variable later you have to use an assign Op with **validate_shape=False.**

Just like any Tensor, variables created with **Variable()** can be used as inputs for other Ops in the graph. Additionally, all the operators overloaded for the Tensor class are carried over to variables, so you can also add nodes to the graph by just doing arithmetic on variables.

In [42]:
my_tensor = tf.constant(2) 
my_variable = tf.Variable(initial_value=my_tensor)
print(my_variable)

<tf.Variable 'Variable_4:0' shape=() dtype=int32_ref>


When you launch the graph, variables have to be explicitly initialized before you can run Ops that use their value.
You can initialize a variable by running its **initializer** op

In [55]:
with tf.Session() as sess:
    sess.run(my_variable.initializer) 
    print(my_variable.eval())         
    


2


The most common initialization pattern is to use the convenience function **global_variables_initializer()** to add an Op to the graph that initializes all the variables. You then run that Op after launching the graph.

In [59]:
# Add an Op to initialize global variables.
init_op = tf.global_variables_initializer()
with tf.Session() as sess:
    # Run the Op that initializes global variables.
    sess.run(init_op)
    print(my_variable.eval())
    



2


### tf.placeholder
tf.placeholder(
    dtype,
    shape=None,
    name=None
)

Inserts a placeholder for a tensor that will be always fed.

Important: This tensor will produce an error if evaluated. Its value must be fed using the **feed_dict** optional argument to **Session.run()**, **Tensor.eval()**, or **Operation.run().**

**Returns:**
A Tensor that may be used as a handle for feeding a value, but not evaluated directly.

In [74]:
x = tf.placeholder(tf.float32,shape=(4,4))
y = tf.matmul(x,x)

with tf.Session() as sess:
  #print(sess.run(y)) # ERROR: will fail because x was not fed.
  rand_array = np.random.rand(4,4)
  print(sess.run(y, feed_dict={x: rand_array}))  # Will succeed.

[[0.6130082  0.92425436 1.1464051  0.8854588 ]
 [0.31513482 0.4386565  0.5960911  0.28097504]
 [1.337853   2.1758783  1.7223178  1.566084  ]
 [0.79207957 1.0890092  0.8528913  0.5445976 ]]
